"""Minimal local terminal interface for Panjeta.

Everything rendered by this module is generated locally in plain Python:
no LLM is involved, no API calls are made, and no tokens are consumed.
UI/input concerns stay out of the agent and LLM layers.
"""

from __future__ import annotations

import sys

# Local startup banner. This text is part of the program, never sent to
# any model and never generated by one.
BANNER = """\
================================
PANJETA AGENT
=============

How would you like to use the agent?

"""

EXIT_WORDS = {"exit", "quit", "q"}


def print_banner(stream=None) -> None:
    """Print the local startup banner (never sent to any LLM)."""
    stream = stream or sys.stdout
    stream.write(BANNER)
    stream.flush()


def read_instruction(prompt: str = "> ") -> str | None:
    """Read one instruction line from the user.

    Returns:
        The trimmed instruction, or None when the input stream ends
        (Ctrl+Z / Ctrl+D) or is interrupted (Ctrl+C).
    """
    try:
        raw = input(prompt)
    except (EOFError, KeyboardInterrupt):
        return None
    return raw.strip()


def is_exit_command(line: str) -> bool:
    """Whether the line is a local exit command (never sent to the LLM)."""
    return line.strip().lower() in EXIT_WORDS


def print_agent_output(text: str, stream=None) -> None:
    """Print the agent's final answer for the current instruction."""
    stream = stream or sys.stdout
    stream.write(f"\nPanjeta: {text}\n")
    stream.flush()