"""Panjeta tool layer: generic registry + concrete built-in tools."""

from src.tools.base import Tool, ToolError
from src.tools.calculator import (
    CALCULATOR_DEFINITION,
    CALCULATOR_NAME,
    calculator_tool,
)
from src.tools.file_manager import (
    COPY_FILE_DEFINITION,
    COPY_FILE_NAME,
    CREATE_FILE_DEFINITION,
    CREATE_FILE_NAME,
    DELETE_FILE_DEFINITION,
    DELETE_FILE_NAME,
    LIST_DIRECTORY_DEFINITION,
    LIST_DIRECTORY_NAME,
    MAX_LIST_ENTRIES,
    MAX_READ_BYTES,
    MOVE_FILE_DEFINITION,
    MOVE_FILE_NAME,
    READ_FILE_DEFINITION,
    READ_FILE_NAME,
    RENAME_FILE_DEFINITION,
    RENAME_FILE_NAME,
    copy_file_tool,
    create_file_tool,
    delete_file_tool,
    list_directory_tool,
    move_file_tool,
    read_file_tool,
    rename_file_tool,
)
from src.tools.files import (
    MAX_RESULTS as SEARCH_FILES_MAX_RESULTS,
    SEARCH_FILES_DEFINITION,
    SEARCH_FILES_NAME,
    search_files_tool,
)
from src.tools.registry import (
    ToolArgumentError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolRegistrationError,
    ToolRegistry,
)

__all__ = [
    "Tool",
    "ToolError",
    "ToolRegistry",
    "ToolRegistrationError",
    "ToolNotFoundError",
    "ToolArgumentError",
    "ToolExecutionError",
    "CALCULATOR_NAME",
    "CALCULATOR_DEFINITION",
    "calculator_tool",
    "SEARCH_FILES_NAME",
    "SEARCH_FILES_DEFINITION",
    "SEARCH_FILES_MAX_RESULTS",
    "search_files_tool",
    "LIST_DIRECTORY_NAME",
    "LIST_DIRECTORY_DEFINITION",
    "list_directory_tool",
    "READ_FILE_NAME",
    "READ_FILE_DEFINITION",
    "read_file_tool",
    "CREATE_FILE_NAME",
    "CREATE_FILE_DEFINITION",
    "create_file_tool",
    "COPY_FILE_NAME",
    "COPY_FILE_DEFINITION",
    "copy_file_tool",
    "MOVE_FILE_NAME",
    "MOVE_FILE_DEFINITION",
    "move_file_tool",
    "RENAME_FILE_NAME",
    "RENAME_FILE_DEFINITION",
    "rename_file_tool",
    "DELETE_FILE_NAME",
    "DELETE_FILE_DEFINITION",
    "delete_file_tool",
    "MAX_LIST_ENTRIES",
    "MAX_READ_BYTES",
]